[package]
name = "rscopula"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"           
statrs = "0.16"         
rand = "0.8"                      
approx = "0.5"             
thiserror = "1.0"         


