[package]
name = "rscopula"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.32"           
statrs = "0.16"         
rand = "0.8"              
rand_distr = "0.4"          
approx = "0.5"             
thiserror = "1.0"         


